version: "3.9"

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "100m"
   max-file: "1"

services:
  nginx:
    image: "nginx:stable-alpine3.17-slim"
    volumes:
    - ./www:/var/www
    - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    logging: *logging
    restart: unless-stopped
    extra_hosts:
      - "nginx:127.0.0.1"
    links:
      - php

  php:
    build: .
    logging: *logging
    volumes:
    - ./www:/var/www
    restart: unless-stopped
    healthcheck:
      test: curl -sS http://nginx | grep works
      interval: 1s
      timeout: 1s
      retries: 3
