apiVersion: v1
kind: Secret
metadata:
  name: sf-auth-nginx
type: kubernetes.io/basic-auth
stringData:
  username: user-sf      # required field for kubernetes.io/basic-auth
  password: password-sf # required field for kubernetes.io/basic-auth