version: "3.9"

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "100m"
   max-file: "1"

services:
  web:
    build: .
    ports:
      - "127.0.0.1:${WEB_PORT}:5000"
    depends_on:
      - redis
    networks:
      - net
    logging: *logging
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    volumes:
    - redis-data:/data
    logging: *logging
    profiles:
      - redis
    restart: unless-stopped
    deploy:
     resources:
       limits:
         cpus: "${DOCKER_WEB_CPUS:-0}"
         memory: "${DOCKER_WEB_MEMORY:-0}"

networks:
 net:

volumes:
 redis-data: